apiVersion: v1
kind: ConfigMap
metadata:
  name: provisioning
  namespace: monitoring
data:
  # Dashboards files.
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: "default"
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards

  # Datasources files.
  datasources.yaml: |
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://prometheus:9090
        is_default: true
        version: 1
        editable: true
