apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
    component: server
spec:
  # todo: need to change to ClusterIP and work with ingress.
  type: NodePort
  selector:
    app: grafana
    component: server
  ports:
    - name: grafana
      protocol: TCP
      port: 3000
      targetPort: 3000
