- name: Redis database exporter deployment playbook.
  connection: local
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Apply Redis database namespace manifest to the cluster.
      community.kubernetes.k8s:
        state: present
        src: /home/arik/kubernetes/platform/resources/manifests/namespaces/redis.yaml

    - name: Apply Redis database exporter service manifest to the cluster.
      community.kubernetes.k8s:
        state: present
        src: /home/arik/kubernetes/platform/redis/manifests/exporter/service.yaml

    - name: Apply Redis database exporter deployment manifest to the cluster.
      community.kubernetes.k8s:
        state: present
        src: /home/arik/kubernetes/platform/redis/manifests/exporter/deployment.yaml
