version: "3.3"

services:
  saleor:
    image: saleor:latest
    container_name: saleor
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    ports:
      - 8000:8000
    networks:
      - main
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
#    command: gunicorn --bind :8000 --workers 1 --worker-class uvicorn.workers.UvicornWorker saleor.asgi:application

  beat:
    image: saleor:latest
    container_name: beat
    restart: unless-stopped
    networks:
      - main
    depends_on:
      - redis
    env_file:
      - .env
    command: celery -A saleor beat

  celery:
    image: saleor:latest
    container_name: celery
    build:
      context: ./saleor
      dockerfile: ./Dockerfile
    restart: unless-stopped
    networks:
      - main
    depends_on:
      - redis
    env_file:
      - .env
    command: celery -A saleor --app=saleor.celeryconf:app worker --loglevel=info

  postgres:
    image: postgres:alpine
    container_name: postgrest
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - main
    env_file:
      - .env
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
    - 6379:6379
    networks:
      - main

networks:
    main:
      driver: bridge

volumes:
  saleor:
    driver: local
