resources:
  # Namespaces.
  - resources/manifests/namespaces/monitoring.yaml
  - resources/manifests/namespaces/postgres.yaml
  - resources/manifests/namespaces/redis.yaml
  - resources/manifests/namespaces/saleor.yaml

  # Secrets.
  - resources/manifests/secrets/postgres.yaml

  # Ingresses.
#  - resources/manifests/ingresses/dashboard.yaml
#  - resources/manifests/ingresses/django.yaml

  # Grafana server.
  - grafana/server/volume.yaml
  - grafana/server/provisioning.yaml
  - grafana/server/dashboards.yaml
  - grafana/server/service.yaml
  - grafana/server/deployment.yaml

  # Postgres database.
  - postgres/database/volume.yaml
  - postgres/database/service.yaml
  - postgres/database/deployment.yaml

  # Postgres exporter.
  - postgres/exporter/secret.yaml
  - postgres/exporter/service.yaml
  - postgres/exporter/deployment.yaml

  # Prometheus server.
  - prometheus/server/config.yaml
  - prometheus/server/service.yaml
  - prometheus/server/deployment.yaml

  # Prometheus Node Exporter.
  - prometheus/exporter/service.yaml
  - prometheus/exporter/daemon.yaml

  # Prometheus Alertmanager.
  - prometheus/alertmanager/config.yaml
  - prometheus/alertmanager/service.yaml
  - prometheus/alertmanager/deployment.yaml

  # Redis database.
  - redis/database/volume.yaml
  - redis/database/config.yaml
  - redis/database/service.yaml
  - redis/database/deployment.yaml

  # Redis exporter.
  - redis/exporter/service.yaml
  - redis/exporter/deployment.yaml

  # Saleor Django server.
  - saleor/manifests/django/secret.yaml
  - saleor/manifests/django/config.yaml
  - saleor/manifests/django/service.yaml
  - saleor/manifests/django/deployment.yaml

  # Saleor Celery worker.
  - saleor/manifests/celery/deployment.yaml
  - saleor/manifests/celery/scale.yaml

  # Saleor Beat scheduler.
  - saleor/manifests/beat/deployment.yaml

  # Saleor Celery Exporter.
  - saleor/manifests/exporter/service.yaml
  - saleor/manifests/exporter/deployment.yaml

  # Saleor Dashboard.
  - dashboard/manifests/dashboard/config.yaml
  - dashboard/manifests/dashboard/service.yaml
  - dashboard/manifests/dashboard/deployment.yaml
