- name: Saleor Kubernetes Platform deployment playbook.
  connection: local
  gather_facts: false
  hosts: localhost
  tasks:
    # todo: try to make multi-layer Dockerfile for the Storefront application.
    # todo: need to share volume with Django, Celery and Beat for media. Can't Share the PDF files without it!
    # todo: need to change the path to relative.
    # todo: Cert manager.
    # todo: create Ingress object for Django, and use Gunicorn as the server.
    # todo: consider changing the populatedb function for the host to be correct, according to the address of the Django server.
    # todo: need to add CD pipelines to GitHub actions. Consider to do it directly to the Raspberry Pi.

#    - name: Include Prometheus server playbooks.
#      include: /home/arik/kubernetes/platform/prometheus/playbooks/server.yaml
#
#    - name: Include Prometheus Alertmanager playbooks.
#      include: /home/arik/kubernetes/platform/prometheus/playbooks/alertmanager.yaml
#
#    - name: Include Prometheus Node Exporter playbooks.
#      include: /home/arik/kubernetes/platform/prometheus/playbooks/exporter.yaml

#    - name: Include Postgres database playbooks.
#      include: /home/arik/kubernetes/platform/postgres/playbooks/database.yaml
#
###    - name: Include Postgres database exporter playbooks.
###      include: /home/arik/kubernetes/platform/redis/playbooks/exporter.yaml
#
#    - name: Include Redis database playbooks.
#      include: /home/arik/kubernetes/platform/redis/playbooks/database.yaml

##    - name: Include Redis Redis database exporter playbooks.
##      include: /home/arik/kubernetes/platform/redis/playbooks/exporter.yaml

    - name: Include Django server playbooks.
      include: /home/arik/kubernetes/platform/saleor/playbooks/django.yaml

    - name: Include Beat scheduler playbooks.
      include: /home/arik/kubernetes/platform/saleor/playbooks/beat.yaml

    - name: Include Celery workers playbooks.
      include: /home/arik/kubernetes/platform/saleor/playbooks/celery.yaml

    - name: Include Saleor Dashboard playbooks.
      include: /home/arik/kubernetes/platform/dashboard/playbooks/dashboard.yaml
