apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres
  labels:
   app: postgres
   component: database
spec:
  type: ClusterIP
  selector:
    app: postgres
    component: database
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
