apiVersion: v1
kind: Service
metadata:
  name: exporter
  namespace: redis
  labels:
    app: redis
    component: exporter
spec:
  type: ClusterIP
  selector:
    app: redis
    component: exporter
  ports:
    - name: exporter
      protocol: TCP
      port: 9121
      targetPort: 9121
