apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: postgres
type: Opaque
stringData:
  # Environment variable can be used to define a different name for the default database.
  POSTGRES_DB: saleor

  # Environment variable used to set an user.
  POSTGRES_USER: saleor

  # Environment variable used to set an user password.
  POSTGRES_PASSWORD: saleor
---
apiVersion: v1
kind: Secret
metadata:
  name: exporter
  namespace: postgres
type: Opaque
stringData:
  # Environment variable can be used to define a different name for the default database.
  POSTGRES_DB: saleor

  # Environment variable used to set an user.
  POSTGRES_USER: saleor

  # Environment variable used to set an user password.
  POSTGRES_PASSWORD: saleor
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: saleor
type: Opaque
stringData:
  # Environment variable can be used to define a different name for the default database.
  POSTGRES_DB: saleor

  # Environment variable used to set an user.
  POSTGRES_USER: saleor

  # Environment variable used to set an user password.
  POSTGRES_PASSWORD: saleor
