- name: Apply Monitoring namespace manifest to the cluster.
  community.kubernetes.k8s:
    state: present
    src: /home/arik/kubernetes/platform/resources/manifests/namespaces/monitoring.yaml

- name: Apply Prometheus Node Exporter service manifest to the cluster.
  community.kubernetes.k8s:
    state: present
    src: /home/arik/kubernetes/platform/prometheus/manifests/exporter/service.yaml

- name: Apply Prometheus Node Exporter daemon manifest to the cluster.
  community.kubernetes.k8s:
    state: present
    src: /home/arik/kubernetes/platform/prometheus/manifests/exporter/daemon.yaml
