- name: Apply Monitoring namespace manifest to the cluster.
  community.kubernetes.k8s:
    state: present
    src: /home/arik/kubernetes/platform/resources/manifests/namespaces/monitoring.yaml

- name: Apply Prometheus server configmap manifest to the cluster.
  community.kubernetes.k8s:
    state: present
    src: /home/arik/kubernetes/platform/prometheus/manifests/server/config.yaml

- name: Apply Prometheus server service manifest to the cluster.
  community.kubernetes.k8s:
    state: present
    src: /home/arik/kubernetes/platform/prometheus/manifests/server/service.yaml

- name: Apply Prometheus server deployment manifest to the cluster.
  community.kubernetes.k8s:
    state: present
    src: /home/arik/kubernetes/platform/prometheus/manifests/server/deployment.yaml
