apiVersion: v1
kind: Service
metadata:
  name: adapter
  namespace: monitoring
  labels:
    app: prometheus
    component: adapter
spec:
  type: ClusterIP
  selector:
    app: prometheus
    component: adapter
  ports:
    - name: prometheus
      protocol: TCP
      port: 6443
      targetPort: 6443
