apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: redis
  labels:
    app: redis
    component: database
spec:
  type: ClusterIP
  selector:
    app: redis
    component: database
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
