apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  namespace: redis
  labels:
    app: redis
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
