apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: monitoring
data:
  # Base configuration file.
  prometheus.yaml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
      evaluation_interval: 15s

    rule_files:
    - '/etc/rules/*.rules'

    scrape_configs:
    - job_name: "Kubernetes cAdvisor"
      scrape_interval: 10s
      kubernetes_sd_configs:
      - role: node
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443

    - job_name: "Nodes Exporters"
      scrape_interval: 10s
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        regex: "monitoring"
        action: keep
      - source_labels: [__meta_kubernetes_endpoints_name]
        regex: "exporter"
        action: keep

    - job_name: "Celery Exporters"
      scrape_interval: 10s
      static_configs:
        - targets: ["exporter.saleor:9540"]
      relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: "Namespace"
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: "Name"

    - job_name: "Postgres Exporters"
      scrape_interval: 10s
      static_configs:
        - targets: ["exporter.postgres:9187"]
      relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: "Namespace"
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: "Name"

    - job_name: "Redis Exporters"
      scrape_interval: 10s
      static_configs:
        - targets: ["exporter.redis:9121"]
      relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: "Namespace"
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: "Name"

    alerting:
      alertmanagers:
      - kubernetes_sd_configs:
          - role: pod
        scheme: http
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace]
          regex: monitoring
          action: keep
        - source_labels: [__meta_kubernetes_pod_label_app]
          regex: prometheus
          action: keep
        - source_labels: [__meta_kubernetes_pod_label_component]
          regex: alertmanager
          action: keep
        - source_labels: [__meta_kubernetes_pod_container_port_number]
          regex:
          action: drop

  # Alerts rule file.
  alerts.rules: |
    groups:
    - name: "DeadMan"
      rules:
      - alert: "DeadMansSwitch"
        expr: vector(1)
        labels:
          severity: deadman
        annotations:
          description: "This is a Dead Man's Switch alert, meant to ensure that the Alerting pipeline is functional."

    - name: "Redis"
      rules:
      - alert: "Memory Load"
        expr: |
          100 - ((redis_memory_used_bytes{job="Redis"} * 100) / redis_memory_max_bytes{job="Redis"}) > 30
        labels:
          severity: warning
        annotations:
          description: "Memory load alert."
      - alert: "Connected Clients"
        expr: |
          redis_connected_clients{job="Redis"} > 12
        labels:
          severity: warning
        annotations:
          description: "Connected clients alert."
