apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
    component: server
spec:
  type: NodePort
  selector:
    app: prometheus
    component: server
  ports:
    - name: prometheus
      protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30091
