apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app: prometheus
    component: alertmanager
spec:
  type: NodePort
  selector:
    app: prometheus
    component: alertmanager
  ports:
    - name: alertmanager
      protocol: TCP
      port: 9093
      targetPort: 9093
      nodePort: 30093