apiVersion: v1
kind: ConfigMap
metadata:
  name: exporter
  namespace: postgres
data:
  # Exclusively accepts the hostname without a username and password component.
  DATA_SOURCE_URI: postgres:5432/postgres?sslmode=disable
