apiVersion: v1
kind: Service
metadata:
  name: exporter
  namespace: postgres
  labels:
    app: postgres
    component: exporter
spec:
  type: ClusterIP
  selector:
    app: postgres
    component: exporter
  ports:
  - name: exporter
    protocol: TCP
    port: 9187
    targetPort: 9187
